# Generated by Django 5.2.5 on 2026-09-17 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangePackage',
            fields=[
                ('package_uuid', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('object_uuid', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(max_length=40)),
                ('device_key', models.CharField(blank=True, db_index=True, max_length=16)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('direction', models.CharField(default='phone_to_vps', max_length=40)),
                ('status', models.CharField(db_index=True, default='uploaded_to_vps', max_length=50)),
                ('channel', models.CharField(default='vps', max_length=40)),
                ('force_upload', models.BooleanField(default=False)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_size', models.PositiveIntegerField(default=0)),
                ('encrypted_payload', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_to_vps_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_by_local_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_local_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_to_phone_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by_phone_at', models.DateTimeField(blank=True, null=True)),
                ('payload_deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileApiKey',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('device_key', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('secret_hash', models.CharField(max_length=64)),
                ('public_name', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['device_key'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='questionnaires.businessregion')),
            ],
            options={
                'ordering': ['sort', 'name'],
                'constraints': [models.UniqueConstraint(fields=('region', 'name'), name='unique_delivery_zone_per_region')],
            },
        ),
        migrations.CreateModel(
            name='ApiNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='questionnaires.mobiledevice')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('device', 'nonce'), name='unique_nonce_per_device')],
            },
        ),
    ]
