# Generated by Django 5.2.5 on 2026-09-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('text', models.TextField()),
                ('kind', models.CharField(max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('sort', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sort', models.PositiveIntegerField(default=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.surveyquestion')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
