# Generated by Django 5.2.5 on 2026-09-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_survey_and_survey_scoped_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepackage',
            name='app_version_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchangepackage',
            name='app_version_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='app_version_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='app_version_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
