# Generated by Django 5.2.5 on 2026-09-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_exchangepackage_app_version_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='visible_to_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
