# Generated by Django 5.2.5 on 2026-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_survey_visible_to_user_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepackage',
            name='workflow_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
